<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KOJOBGV" failures="0" tests="1" name="com.mohs10.Report.PDFReportTest" time="1.847" errors="1" timestamp="2023-05-02T12:33:24 IST" skipped="0">
  <testcase classname="com.mohs10.Report.PDFReportTest" name="PDFreports" time="1.847">
    <error message="I/O exception." type="com.itextpdf.io.IOException">
      <![CDATA[com.itextpdf.io.IOException: I/O exception.
at com.itextpdf.io.image.ImageDataFactory.readImageType(ImageDataFactory.java:601)
at com.itextpdf.io.image.ImageDataFactory.createImageInstance(ImageDataFactory.java:518)
at com.itextpdf.io.image.ImageDataFactory.create(ImageDataFactory.java:101)
at com.itextpdf.io.image.ImageDataFactory.create(ImageDataFactory.java:121)
at com.itextpdf.io.image.ImageDataFactory.create(ImageDataFactory.java:131)
at com.mohs10.Report.PDFReportTest.PDFreports(PDFReportTest.java:200)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.FileNotFoundException: C:\Users\DELL\Desktop\drivers\painite_latest-master\painite_latest-master\Demo-Painite-master\TestcaseScreenshotslogin.png (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
at java.base/java.net.URL.openStream(URL.java:1161)
at com.itextpdf.io.util.UrlUtil.openStream(UrlUtil.java:103)
at com.itextpdf.io.image.ImageDataFactory.readImageType(ImageDataFactory.java:596)
... 33 more
]]>
    </error>
  </testcase> <!-- PDFreports -->
  <system-out/>
</testsuite> <!-- com.mohs10.Report.PDFReportTest -->
